CREATE TABLE TBL_EMPLOYEE(
	ID NUMBER CONSTRAINT PK_EMPLOYEE PRIMARY KEY,
	EMPLOYEE_NAME VARCHAR2(255)
);






CREATE TABLE TBL_INCOME(
	ID NUMBER CONSTRAINT PK_INCOME PRIMARY KEY,
	INCOME NUMBER,
	INCOME_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	EMPLOYEE_ID NUMBER,
	CONSTRAINT FK_INCOME_EMPLOYEE FOREIGN KEY(EMPLOYEE_ID)
	REFERENCES TBL_EMPLOYEE(ID)
);

SELECT * FROM TBL_INCOME;
INSERT INTO TBL_EMPLOYEE
VALUES(1, '홍길동');
INSERT INTO TBL_EMPLOYEE
VALUES(2, '장보고');
INSERT INTO TBL_EMPLOYEE
VALUES(3, '이순신');

INSERT INTO TBL_INCOME (ID, INCOME, EMPLOYEE_ID)
VALUES(1, 100000, 1);
INSERT INTO TBL_INCOME (ID, INCOME, EMPLOYEE_ID)
VALUES(2, 150000, 1);

SELECT TE.EMPLOYEE_NAME, NVL(SUM(INCOME), 0) FROM TBL_INCOME TI RIGHT JOIN TBL_EMPLOYEE TE ON TI.EMPLOYEE_ID = TE.ID GROUP BY EMPLOYEE_NAME;

