-- 요구사항
-- 회사에서 광고를 여럭개 신청하려고 합니다
-- 회사, 광고, 신청 테이블을 만들어 주세요.

CREATE SEQUENCE SEQ_COMPANY;
CREATE TABLE TBL_COMPANY(
	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
	COMPANY_NAME VARCHAR(255) NOT NULL UNIQUE,
	COMPANY_PHONE VARCHAR(255) NOT NULL,
	COMPANY_ADDRESS VARCHAR(255)
);

CREATE SEQUENCE SEQ_ADVER;
CREATE TABLE TBL_ADVER (
	ID NUMBER CONSTRAINT PK_ADVER PRIMARY KEY,
	ADVER_TITLE VARCHAR(255),
	ADVER_CONTENT VARCHAR(255)
);

CREATE SEQUENCE SEQ_ADVER_FORM;
CREATE TABLE TBL_ADVER_FORM(
   ID NUMBER CONSTRAINT PK_ADVER_FORM PRIMARY KEY,
   COMPANY_ID NUMBER,
   ADVER_ID NUMBER,
   CONSTRAINT FK_ADVER_FORM_COMPANY FOREIGN KEY(COMPANY_ID)
   REFERENCES TBL_COMPANY(ID),
   CONSTRAINT FK_ADVER_FROM_ADVER FOREIGN KEY(ADVER_ID)
   REFERENCES TBL_ADVER(ID)
);

-- 요구 사항
-- 회원이 존재하고 회원은 여러 상품을 구매할 수 있습니다.
-- 데이터 베이스 시스템을 만들어주세요.
-- MEMBER
-- 이름, 나이, 핸드폰, 주소, 등급, ...
CREATE SEQUENCE SEQ_MEMBER2;
CREATE TABLE TBL_MEMBER2(
	ID NUMBER CONSTRAINT PK_MEMBER2 PRIMARY KEY,
	MEMBER_NAME VARCHAR(255),
	MEMBER_AGE NUMBER,
	MEMBER_ADDRESS VARCHAR(255),
	MEMBER_PHONE VARCHAR(255) DEFAULT '000-0000-0000',
	MEMBER_GRADE CHAR(5)
);

DROP TABLE TBL_MEMBER2;


-- PRODUCT
-- 이름, 가격, 재고, 생산지, 생산일, ...
CREATE SEQUENCE SEQ_PRODUCT2;
CREATE TABLE TBL_PRODUCT2(
	ID NUMBER CONSTRAINT PK_PRODUCT2 PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255),
	PRODUCT_PRICE NUMBER,
	PRODUCT_STOCK NUMBER,
	PRODUCT_MOU VARCHAR2(255),
	PRODUCT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE TBL_PRODUCT2;
-- ORDER
-- 회원_ID, 상품_ID, 주문일자, ...
CREATE SEQUENCE SEQ_ORDER2;
CREATE TABLE TBL_ORDER2(
	ID NUMBER CONSTRAINT PK_ORDER2 PRIMARY KEY,
	ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER2(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT2(ID)
);


--① 미술학원 관리 시스템
--
--요구사항
--미술학원에서는 학생들이 수업을 신청해야 합니다.
--학생은 이름, 나이, 연락처가 필요하고 학생은 5살 이상 18살 이하입니다.
--강사는 이름, 담당과목, 경력연수가 필요합니다. 담당과목은 수체화, 유화, 드로잉, 조소 중 하나만 허용합니다.
--수업은 수업명, 수업내용, 수업시간이 필요하고
--학생은 여러 개의 수업에 신청할 수 있습니다.

CREATE SEQUENCE SEQ_STUDENT;
CREATE TABLE TBL_STUDENT(
	ID NUMBER PK_STUDENT PRIMARY KEY,
	STUDENT_NAME VARCHAR2(255) NOT NULL,
	STUDENT_AGE NUMBER CONSTRAINT CHILD_AGE CHECK(STUDENT_AGE IN (BETWEEN 5 TO 18)) NOT NULL,
	STUDENT_PHONE VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_TEACHER;
CREATE TABLE TBL_TEACHER(
	ID NUMBER CONSTRAINT PK_TEACHER PRIMARY KEY,
	TEACHER_NAME VARCHAR2(255) NOT NULL,
	TEACHER_SUBJECT VARCHAR2(255) CONSTRAINT SUBJECT_TYPE CHECK (TEACHER_SUBJECT IN ('수체화', '유화', '드로잉', '조소')) NOT NULL,
	TEACHER_YEAR NUMBER NOT NULL
);

CREATE SEQUENCE SEQ_CLASS;
CREATE TABLE TBL_CLASS(
	ID NUMBER CONSTRAINT PK_CLASS PRIMARY KEY,
	CLASS_NAME VARCHAR2(255) NOT NULL,
	CLASS_CONTENT VARCHAR2(255) NOT NULL,
	CLASS_TIME VARCHAR2(255) NOT NULL,
	TEACHER_ID NUMBER,
	CONSTRAINT FK_CLASS_TEACHER FOREIGN KEY(TEACHER_ID)
	REFERENCES TBL_TEACHER(ID)
);

CREATE SEQUENCE SEQ_CHOICE;
CREATE TABLE TBL_CHOICE(
	ID NUMBER CONSTRIANT PK_CHOICE PRIMARY KEY,
	STUDENT_ID NUMBER,
	CLASS_ID NUMBER,
	CONSTRAINT FK_CHOICE_STUDENT FOREIGN KEY(STUDENT_ID)
	REFERENCES TBL_STUDENT(ID),
	CONSTRAINT FK_CHOICE_CLASS FOREIGN KEY(CLASS_ID)
	REFERENCES TBL_CLASS(ID)
);






