CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER,
	USER_ADDRESS VARCHAR2(255)
);

-- 상품 PRODUCT
-- 상품 이름, 상품 가격, 상품 재고, 상품 설명
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999,
	PRODUCT_CONTEXT VARCHAR2(255)
);

DROP TABLE TBL_PRODUCT ;

-- SQL언어의 값은 '' 싱글쿼터를 사용한다.
INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE )
VALUES(SEQ_PRODUCT.NEXTVAL, '이승찬의 맥북', 1500000);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE )
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램', 1500);

INSERT INTO TBL_PRODUCT(ID, PRODUCT_NAME, PRODUCT_PRICE )
VALUES(SEQ_PRODUCT.NEXTVAL, '배승원의 그램3', 1500);

SELECT * FROM TBL_PRODUCT ;
--DROP SEQUENCE SEQ_PRODUCT;

-- 컬럼 추가
ALTER TABLE TBL_PRODUCT ADD REVIEW_COUNT NUMBER ;

-- 컬럼 수정
ALTER TABLE TBL_PRODUCT MODIFY REVIEW_COUNT NUMBER DEFAULT 0;

-- 컬럼 삭제
ALTER TABLE TBL_PRODUCT DROP COLUMN REVIEW_COUNT;

-- 멤버 테이블 
-- 이름, 나이, 성별, 주소
-- 사용자를 2명 추가
-- 등급 컬럼 CHAR 추가
-- 등급 컬럼을 VARCHAR2로 변경
-- 등급 컬럼 삭제
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(255),
	MEMBER_AGE NUMBER,
	MEMBER_GENDER CHAR(5),
	MEMBER_ADDRESS VARCHAR2(255)
);

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '이태희', 25, '여', '경기도 고양시');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '차은우', 22, '남', '서울시 강남구');

ALTER TABLE TBL_MEMBER ADD GRADE CHAR(10);

ALTER TABLE TBL_MEMBER MODIFY GRADE VARCHAR2(255);

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '장원영', 21, '여', '서울시 강남구' );

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS)
VALUES(SEQ_MEMBER.NEXTVAL, '카리나', 22, '여', '서울시 강남구');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS, GRADE)
VALUES(SEQ_MEMBER.NEXTVAL, '장원영', 21, '여', '서울시 강남구' , '골드');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS, GRADE)
VALUES(SEQ_MEMBER.NEXTVAL, '카리나', 22, '여', '서울시 강남구' , '실버');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS, GRADE)
VALUES(SEQ_MEMBER.NEXTVAL, '카리나', 22, '여', '서울시 강남구' , 'ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ');

INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_GENDER, MEMBER_ADDRESS, GRADE)
VALUES(SEQ_MEMBER.NEXTVAL, '카리나', 22, '남', '서울시 강남구' , 'ㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇㅇ');

SELECT * FROM TBL_MEMBER;
	
ALTER TABLE TBL_MEMBER DROP COLUMN GRADE;




