--회원: (회원ID, 이메일, 비밀번호, 주소, 생년월일)
CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
	MEMBER_BIRTH DATE
);
--
--도서: (도서ID, 제목, 저자, 가격, 재고수량)
CREATE SEQUENCE SEQ_BOOK;
CREATE TABLE TBL_BOOK(
	ID NUMBER CONSTRAINT PK_BOOK PRIMARY KEY,
	BOOK_TITLE VARCHAR2(255) NOT NULL,
	BOOK_AUTHOR VARCHAR2(255) NOT NULL,
	BOOK_PRICE NUMBER NOT NULL,
	BOOK_STOCK NUMBER DEFAULT 999
);
--대출: (대출ID, 대출일, 반납여부[Y/N])
CREATE SEQUENCE SEQ_LOAN;
CREATE TABLE TBL_LOAN(
	ID NUMBER CONSTRAINT PK_LOAN PRIMARY KEY,
	LOAN_DATE DATE,
	LOAN_STATUS CHAR(5) DEFAULT 'N' CONSTRAINT STATUS_TYPE CHECK (LOAN_STATUS IN('Y', 'N')),
	MEMBER_ID NUMBER,
	BOOK_ID NUMBER,
	CONSTRAINT FK_LOAN_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_LOAN_BOOK FOREIGN KEY(BOOK_ID)
	REFERENCES TBL_BOOK(ID)
);

--
--리뷰: (리뷰ID, 내용, 평점[1~5], 작성일)
CREATE SEQUENCE SEQ_REVIEW;
CREATE TABLE TBL_REVIEW(
	ID NUMBER CONSTRAINT PK_REVIEW PRIMARY KEY,
	REVIEW_CONTENT VARCHAR2(255) NOT NULL,
	REVIEW_STAR NUMBER DEFAULT 3 CONSTRAINT STAR_NUMBER CHECK (REVIEW_STAR BETWEEN 1 AND 5),
	REVIEW_DATE DATE,	
	MEMBER_ID NUMBER,
	BOOK_ID NUMBER,
	CONSTRAINT FK_REVIEW_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_REVIEW_BOOK FOREIGN KEY(BOOK_ID)
	REFERENCES TBL_BOOK(ID)
);



