CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_AGE NUMBER,
	MEMBER_ADDRESS VARCHAR2(255)
);

SELECT * FROM TBL_MEMBER;
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'lth12345', '1234', '이태희', 27, '경기도 고양시');
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'lth123456', '12345', '이태희', 27, '경기도 고양시');
INSERT INTO TBL_MEMBER VALUES (SEQ_MEMBER.NEXTVAL, 'karina123', '1234', '카리나', 22, '서울시 강남구');

