--상황: 영화와 배우 정보를 관리하는 데이터베이스입니다. 영화 정보와 영화에 출연한 배우 정보를 담는 두 개의 테이블을 만드세요.
--
--영화(Movies) 테이블
--
--영화ID (기본 키)
--
--영화제목
--
--개봉연도
--
--출연(Casts) 테이블
--
--배우ID (기본 키)
--
--영화ID (어떤 영화에 출연했는지 연결하는 외래 키)
--
--배우이름
--
--역할


CREATE SEQUENCE SEQ_MOVIE;
CREATE TABLE TBL_MOVIE(
	ID NUMBER CONSTRAINT PK_MOVIE PRIMARY KEY,
	MOVIE_TITLE VARCHAR2(255) NOT NULL,
	MOVIE_YEAR NUMBER
);



CREATE SEQUENCE SEQ_CAST;
CREATE TABLE TBL_CAST(
	ID NUMBER CONSTRAINT PK_CAST PRIMARY KEY,
	CAST_NAME VARCHAR2(255) NOT NULL,
	CAST_ROLE VARCHAR2(255) NOT NULL,
	MOVIE_ID NUMBER,
	CONSTRAINT FK_CAST_MOVIE FOREIGN KEY(MOVIE_ID)
	REFERENCES TBL_MOVIE(ID)
);

DROP TABLE TBL_MOVIE;
--- TBL_MOVIE 테이블에 데이터 삽입
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '이터널스', 2021);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '스파이더맨: 노 웨이 홈', 2021);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '듄', 2021);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '닥터 스트레인지: 대혼돈의 멀티버스', 2022);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '탑건: 매버릭', 2022);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '아바타: 물의 길', 2022);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '더 퍼스트 슬램덩크', 2023);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '오펜하이머', 2023);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '바비', 2023);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '서울의 봄', 2023);
INSERT INTO TBL_MOVIE(ID, MOVIE_TITLE, MOVIE_YEAR) VALUES (SEQ_MOVIE.NEXTVAL, '기생충', 2021);

--- TBL_CAST 테이블에 데이터 삽입

INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '안젤리나 졸리', '주연', 1); -- 이터널스
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '리처드 매든', '주연', 1); -- 이터널스
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '톰 홀랜드', '주연', 2); -- 스파이더맨: 노 웨이 홈
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '젠데이아', '주연', 2); -- 스파이더맨: 노 웨이 홈
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '티모시 샬라메', '주연', 3); -- 듄
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '레베카 퍼거슨', '조연', 3); -- 듄
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '베네딕트 컴버배치', '주연', 4); -- 닥터 스트레인지: 대혼돈의 멀티버스
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '엘리자베스 올슨', '조연', 4); -- 닥터 스트레인지: 대혼돈의 멀티버스
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '톰 크루즈', '주연', 5); -- 탑건: 매버릭
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '마일즈 텔러', '조연', 5); -- 탑건: 매버릭
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '샘 워싱턴', '주연', 6); -- 아바타: 물의 길
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '조 샐다나', '주연', 6); -- 아바타: 물의 길
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '송태섭', '주연', 7); -- 더 퍼스트 슬램덩크
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '강백호', '주연', 7); -- 더 퍼스트 슬램덩크
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '킬리언 머피', '주연', 8); -- 오펜하이머
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '에밀리 블런트', '조연', 8); -- 오펜하이머
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '마고 로비', '주연', 9); -- 바비
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '라이언 고슬링', '주연', 9); -- 바비
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '황정민', '주연', 10); -- 서울의 봄
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '정우성', '주연', 10);
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '송강호', '주연', 11);
INSERT INTO TBL_CAST(ID, CAST_NAME, CAST_ROLE, MOVIE_ID) VALUES(SEQ_CAST.NEXTVAL, '송강호', '주연', 10);



-- 모든 영화의 제목과 해당 영화의 개봉 연도를 조회하시오.
SELECT MOVIE_TITLE, MOVIE_YEAR FROM TBL_MOVIE;
SELECT tbm.MOVIE_TITLE, tbm.MOVIE_YEAR FROM TBL_CAST tbc JOIN TBL_MOVIE tbm ON tbc.movie_id = TBM.iD;

-- 2023년에 개봉한 모든 영화의 제목을 조회하시오.
SELECT MOVIE_TITLE FROM TBL_MOVIE WHERE MOVIE_YEAR = 2023;

-- 출연한 배우 이름이 '톰 크루즈'인 영화의 제목을 조회하시오.
SELECT MOVIE_TITLE FROM TBL_MOVIE;
SELECT TBM.MOVIE_TITLE FROM TBL_CAST TBC JOIN TBL_MOVIE TBM ON TBC.MOVIE_ID = TBM.ID WHERE CAST_NAME = '톰 크루즈';

-- 영화 제목에 '서울'이라는 단어가 포함된 모든 영화의 제목과 개봉 연도를 조회하시오.
SELECT MOVIE_TITLE, MOVIE_YEAR FROM TBL_MOVIE WHERE MOVIE_TITLE LIKE '%서울%';

--각 개봉 연도별로 몇 편의 영화가 있는지 연도와 영화 수를 함께 조회하시오.
SELECT COUNT(ID) || '개', MOVIE_YEAR FROM TBL_MOVIE GROUP BY MOVIE_YEAR;

--  영화 제목과 해당 영화에 출연한 모든 배우의 이름을 함께 조회하시오.
SELECT MOVIE_TITLE FROM TBL_MOVIE;
SELECT MOVIE_TITLE, CAST_NAME 
FROM TBL_CAST TBC 
JOIN TBL_MOVIE TBM 
ON TBC.MOVIE_ID = TBM.ID 
WHERE TBM.ID 
IN (
	SELECT ID 
	FROM TBL_MOVIE
);

--출연한 배우가 2명 이상인 영화의 제목을 조회하시오.
SELECT MOVIE_TITLE FROM TBL_MOVIE;
--SELECT CAST_NAME FROM TBL_CAST WHERE ID > 2;
SELECT MOVIE_TITLE 
FROM TBL_CAST TBC 
JOIN TBL_MOVIE TBM 
ON TBC.MOVIE_ID = TBM.ID 
WHERE TBM.ID 
IN (
	SELECT ID FROM TBL_MOVIE
) 
GROUP BY MOVIE_TITLE  
HAVING COUNT(TBM.ID) >= 2;

--2022년과 2023년에 개봉한 영화들의 제목을 연도별로 오름차순 정렬하여 조회하시오.
SELECT MOVIE_TITLE FROM TBL_MOVIE WHERE MOVIE_YEAR BETWEEN 2022 AND 2023 ORDER BY ID ASC;

-- '주연' 역할을 한 배우의 이름과 그 배우가 출연한 영화의 제목을 모두 조회하시오.
SELECT MOVIE_TITLE FROM TBL_MOVIE;
SELECT MOVIE_TITLE, CAST_NAME 
FROM TBL_CAST TBC 
JOIN TBL_MOVIE TBM 
ON TBC.MOVIE_ID = TBM.ID 
WHERE CAST_ROLE = '주연';

-- 가장 많은 영화에 출연한 배우의 이름과 출연 영화 수를 조회하시오.
SELECT CAST_NAME, COUNT(MOVIE_ID) FROM TBL_CAST TBC JOIN TBL_MOVIE TBM ON TBC.MOVIE_ID = TBM.ID GROUP BY CAST_NAME;
