--TBL_STUDENT(ID, STU_NAME, MAJOR, GENDER, BIRTHDATE)
--
--TBL_COURSE(ID, COURSE_NAME, DEPT, CREDIT)
--
--TBL_ENROLL(ID, STU_ID FK→STUDENT.ID, COURSE_ID FK→COURSE.ID, GRADE, ENROLL_DATE)

CREATE SEQUENCE SEQ_STUDENT;
CREATE TABLE TBL_STUDENT(
	ID NUMBER CONSTRAINT PK_STUDENT PRIMARY KEY,
	STUDENT_NAME VARCHAR2(255) NOT NULL,
	STUDENT_MAJOR VARCHAR2(255) NOT NULL,
	STUDENT_GENDER CHAR(10) CONSTRAINT STUDENT_GENDER_TYPE CHECK (STUDENT_GENDER IN ('남', '여')),
	STUDENT_BIRTHDATE DATE
);

CREATE SEQUENCE SEQ_COURSE;
CREATE TABLE TBL_COURSE(
	ID NUMBER CONSTRAINT PK_COURSE PRIMARY KEY,
	COURSE_NAME VARCHAR2(255),
	COURSE_DEFT VARCHAR2(255),
	COURSE_CREDIT NUMBER
);

CREATE SEQUENCE SEQ_ENROLL;
CREATE TABLE TBL_ENROLL(
	ID NUMBER CONSTRAINT PK_ENROLL PRIMARY KEY,
	ENROLL_GRADE NUMBER,
	ENROLL_DATE DATE DEFAULT CURRENT_DATE,
	STUDENT_ID NUMBER,
	COURSE_ID NUMBER,
	CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STUDENT_ID)
	REFERENCES TBL_STUDENT(ID),
	CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COURSE_ID)
	REFERENCES TBL_COURSE(ID)
);
-- 학생 ID는 1~6, 과목 ID는 1~10 범위
-- 성적(ENROLL_GRADE)은 1~4 범위, 날짜는 샘플로 적절히 배분
-- 학생 6명
INSERT INTO TBL_STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '김철수', '컴퓨터공학', '남', DATE '2000-03-08');
INSERT INTO TBL_STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '이영희', '경영학',     '여', DATE '2001-07-15');
INSERT INTO TBL_STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '박민수', '전자공학',   '남', DATE '1999-12-30');
INSERT INTO TBL_STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '정수진', '수학',       '여', DATE '2002-05-21');
INSERT INTO TBL_STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '최유리', '영문학',     '여', DATE '2000-11-02');
INSERT INTO TBL_STUDENT VALUES (SEQ_STUDENT.NEXTVAL, '오지훈', '체육학',     '남', DATE '1998-09-10');

-- 과목 10개
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '데이터베이스', '컴퓨터공학', 3);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '운영체제',     '컴퓨터공학', 3);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '알고리즘',     '컴퓨터공학', 3);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '마케팅원론',   '경영학',     2);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '재무관리',     '경영학',     3);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '회로이론',     '전자공학',   3);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '선형대수',     '수학',       3);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '영문학개론',   '영문학',     2);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '스포츠생리학', '체육학',     2);
INSERT INTO TBL_COURSE VALUES (SEQ_COURSE.NEXTVAL, '통계학',       '수학',       3);



INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-01', 1, 1); -- 김철수, 데이터베이스
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-02', 1, 2); -- 김철수, 운영체제
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 2, DATE '2024-03-03', 1, 4); -- 김철수, 마케팅원론

INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-01', 2, 4); -- 이영희, 마케팅원론
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-02', 2, 5); -- 이영희, 재무관리
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 2, DATE '2024-03-03', 2, 8); -- 이영희, 영문학개론

INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-01', 3, 6); -- 박민수, 회로이론
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-02', 3, 1); -- 박민수, 데이터베이스
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-03', 3, 2); -- 박민수, 운영체제

INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-01', 4, 7); -- 정수진, 선형대수
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 2, DATE '2024-03-02', 4, 10);-- 정수진, 통계학
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-03', 4, 3); -- 정수진, 알고리즘

INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-01', 5, 8); -- 최유리, 영문학개론
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-02', 5, 4); -- 최유리, 마케팅원론
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 2, DATE '2024-03-03', 5, 9); -- 최유리, 스포츠생리학

INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-01', 6, 9); -- 오지훈, 스포츠생리학
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-02', 6, 6); -- 오지훈, 회로이론
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 3, DATE '2024-03-03', 6, 7); -- 오지훈, 선형대수
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 2, DATE '2024-03-04', 6, 10);-- 오지훈, 통계학
INSERT INTO TBL_ENROLL VALUES (SEQ_ENROLL.NEXTVAL, 4, DATE '2024-03-05', 6, 1); -- 오지훈, 데이터베이스


